# Generated by Django 3.2.14 on 2022-08-03 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systemandfacility', '0005_department_location'),
        ('workorder', '0002_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_discription', models.CharField(max_length=50)),
                ('discription', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='workorder.category')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='systemandfacility.facility')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='systemandfacility.location')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='workorder.priority')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSpent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('workorder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_spent', to='workorder.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workorder.workorder')),
            ],
        ),
    ]
