# Generated by Django 3.2.14 on 2022-09-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0007_alter_workorder_enter_device_id_manually'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_orders_connected_to_an_asset',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=50),
        ),
    ]
