# Generated by Django 3.2.14 on 2022-09-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0009_rename_assigned_workorder_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='timespent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
