# Generated by Django 3.2.14 on 2022-10-23 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_asset_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0011_alter_workorder_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='asset',
            field=models.ManyToManyField(blank=True, related_name='work_orders', to='asset.Asset'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
