# Generated by Django 3.2.14 on 2022-10-10 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0012_auto_20220916_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 13, 27, 15, 806635), null=True),
        ),
    ]
