# Generated by Django 3.2.14 on 2022-10-18 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0015_alter_workorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 18, 17, 47, 25, 815405), null=True),
        ),
    ]
