# Generated by Django 3.2.14 on 2022-10-19 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0016_alter_workorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 19, 19, 38, 38, 758270), null=True),
        ),
    ]
