# Generated by Django 3.2.14 on 2022-08-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemandfacility', '0005_department_location'),
        ('asset', '0003_auto_20220805_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('ready_to_start', 'Ready to start'), ('in_progress', 'In progress'), ('waiting_for_approval', 'Wait for Approval'), ('complete', 'Complete')], default='ready_to_start', max_length=50)),
                ('frequency', models.CharField(choices=[('every_day', 'Every Day'), ('every_week', 'Every Week'), ('monthly', 'Monthly'), ('quaterly', 'Quaterly'), ('semi', 'Semi'), ('annual', 'Annual'), ('tri-annual', 'Tri-Annual'), ('5-years', '5-Year')], default='monthly', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.FileField(upload_to='images/')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_maintenance', to='asset.asset')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_maintenances', to='systemandfacility.facility')),
            ],
        ),
    ]
