# Generated by Django 3.2.14 on 2022-08-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemandfacility', '0005_department_location'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('barcode', models.IntegerField()),
                ('is_demo', models.BooleanField(default=False)),
                ('attribute_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset.assetattributeset')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='systemandfacility.facility')),
            ],
        ),
    ]
