# Generated by Django 3.2.14 on 2022-09-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20220909_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='type',
            new_name='asset_type',
        ),
    ]
