# Generated by Django 3.2.14 on 2022-10-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemandfacility', '0005_department_location'),
        ('asset', '0005_rename_type_asset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='systemandfacility.location'),
        ),
    ]
