# Generated by Django 3.2.14 on 2022-07-28 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemandfacility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='systemandfacility.system')),
            ],
        ),
    ]
