# Generated by Django 3.2.14 on 2022-07-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemandfacility', '0003_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='systemandfacility.building')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='systemandfacility.facility')),
            ],
        ),
    ]
