# Generated by Django 3.2.14 on 2022-07-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemandfacility', '0004_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='systemandfacility.building')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='systemandfacility.facility')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='systemandfacility.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_location', models.CharField(max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='systemandfacility.building')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='systemandfacility.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='systemandfacility.facility')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='systemandfacility.floor')),
            ],
        ),
    ]
