# Generated by Django 3.2.16 on 2022-11-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20221103_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='question',
        ),
        migrations.AddField(
            model_name='questionset',
            name='question',
            field=models.ManyToManyField(related_name='questionsets', to='question.Question'),
        ),
    ]
