# Generated by Django 3.2.14 on 2022-11-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20221118_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
    ]
