# Generated by Django 3.2.14 on 2022-10-23 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preventivemaintenance', '0001_initial'),
        ('question', '0002_alter_question_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type_text', models.TextField(blank=True, null=True)),
                ('answer_type_integer', models.IntegerField(blank=True, null=True)),
                ('answer_type_float', models.FloatField(blank=True, null=True)),
                ('answer_type_boolean', models.BooleanField(blank=True, null=True)),
                ('answer_type_image', models.ImageField(blank=True, null=True, upload_to='answer/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_fail', models.BooleanField(default=False)),
                ('preventive_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='preventivemaintenance.preventivemaintenance')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='question.question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
